version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nest-app:
    build:
      context: ./nest-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./nest-app:/app
      - /app/node_modules
    command: sh -c "sleep 10 && npx prisma generate && npx prisma db push && npx nest build && npx nest start"

  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - BACKEND_URL_PRIVATE=${BACKEND_URL_PRIVATE}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - BACKEND_URL_PRIVATE=${BACKEND_URL_PRIVATE}
    env_file:
      - .env

volumes:
  db-data:
